package pro3.shoppingCart;
import java.io.IOException;
import java.io.PrintWriter;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;


public class orderConfirm extends HttpServlet {
	public void doGet(HttpServletRequest req,
			HttpServletResponse resp)throws ServletException, IOException {		
		resp.setContentType("text/html;charset=UTF-8");	
		PrintWriter out = resp.getWriter();
		
		out.print("<!DOCTYPE HTML PUBLIC '-//W3C//DTD HTML 4.01 Transitional//EN'>")  ;   
		out.print("<html>       ");
		out.print("	<head>       ");
		out.print("		<title>达内电子商务门户</title>       ");
		out.print("		<meta http-equiv='Content-Type' content='text/html; charset=utf-8'>       ");
		out.print("		<meta name='description' content='达内电子商务门户'>       ");
		out.print("		<link href='css/tarena.css' rel=stylesheet>       ");
		out.print("	</head>       ");
		out.print("	<body topmargin='0' leftmargin='0' rightmargin='0' bottommargin='0'>       ");
		out.print("	       ");
		out.print("<!-- Header Start -->       ");
		out.print("       ");
		out.print("		<table width='100%' border='0' cellspacing='0' cellpadding='0' id='table2'>       ");
		out.print("			<tr>       ");
		out.print("				<td align='left' width='7%' background='images/top_bg.gif'><img src='images/logo.gif' width='286' height='58'></td>       ");
		out.print("				<td width='62%' background='images/top_bg.gif'>　</td>       ");
		out.print("				<td width='31%' background='images/top_bg.gif' align='right'><img src='images/top_r.gif' width='352' height='58' border='0'></td>       ");
		out.print("			</tr>       ");
		out.print("		</table>       ");
		out.print("		       ");
		out.print("		<table width='100%' border='0' cellspacing='0' cellpadding='0'>       ");
		out.print("			<tr>       ");
		out.print("				<td background='images/dh_bg.gif' align='left' height='12'>       ");
		out.print("					<table width='100' border='0' cellspacing='0' cellpadding='0' align='center'>       ");
		out.print("						<tr>       ");
		out.print("							<td width='5%'></td>       ");
		out.print("							       ");
		out.print("          <td width='10%'><a href='../product/productList'><img name='Image1' border='0' src='images/index.gif' width='90' height='36'></a></td>       ");
		out.print("							       ");
		out.print("          <td width='10%'><a href='../user/userManage'><img name='Image2' border='0' src='images/reg.gif' width='92' height='36'></a></td>       ");
		out.print("							       ");
		out.print("          <td width='10%'><a href='../shoppingCart/shoppingCart'><img name='Image4' border='0' src='images/cart.gif' width='92' height='36'></a></td>       ");
		out.print("							       ");
		out.print("          <td width='10%'><a href='../order/orderList'><img name='Image5' border='0' src='images/order.gif' width='92' height='36'></a></td>       ");
		out.print("							       ");
		out.print("          <td width='10%'><a href='../product/productList'><img name='Image6' border='0' src='images/exit.gif' width='92' height='36'></a></td>       ");
		out.print("						</tr>       ");
		out.print("					</table>       ");
		out.print("				</td>       ");
		out.print("			</tr>       ");
		out.print("		</table>       ");
		out.print("		       ");
		out.print("		<table cellspacing='1' cellpadding='3' align='center' border='0' width='98%'>       ");
		out.print("			<tr>       ");
		out.print("				<td width='65%'><br>       ");
		out.print("					>> 欢迎访问 <b>达内电子商务门户</b>       ");
		out.print("				</td>       ");
		out.print("				<td width='35%' align='right'>       ");
		out.print("				</td>       ");
		out.print("			</tr>       ");
		out.print("		</table>       ");
		out.print("		       ");
		out.print("<!-- Header End -->       ");
		out.print("       ");
		out.print("<!-- Body Start -->       ");
		out.print("	<form>       ");
		out.print("		<table cellspacing='1' cellpadding='3' align='center' class='tableBorder2'>       ");
		out.print("			<tr>       ");
		out.print("				<td height='25' valign='middle'>       ");
		out.print("					<img src='images/Forum_nav.gif' align='absmiddle'>       ");
		out.print("					<a href=index.jsp>达内电子商务门户</a> →&nbsp<img border='0' src='images/dog.gif' width='19' height='18'>&nbsp订单确认       ");
		out.print("				</td>       ");
		out.print("			</tr>       ");
		out.print("		</table>       ");
		out.print("		       ");
		out.print("		<br>       ");
		out.print("		       ");
		out.print("		<table cellspacing='1' cellpadding='3' align='center' class='tableborder1'>       ");
		out.print("			<tr>       ");
		out.print("				<td valign='middle' align='center' height='25' background='images/bg2.gif' width='8%' colspan='2'>       ");
		out.print("						<font color='#ffffff' size='2pt'>       ");
		out.print("							<b>用户信息</b>       ");
		out.print("						</font>       ");
		out.print("						<input type='button' value='修改' onclick='javascript:window.location='../user/userModify';'>       ");
		out.print("				</td>       ");
		out.print("			</tr>       ");
		out.print("			<tr>       ");
		out.print("				<td class=tablebody2 valign='middle' align='right' width='40%'>用户名&nbsp:&nbsp</td>       ");
		out.print("				<td class=tablebody1>tarena</td>       ");
		out.print("			</tr>       ");
		out.print("			<tr>       ");
		out.print("				<td class=tablebody2 align='right'>联系地址&nbsp:&nbsp</td>       ");
		out.print("				<td class=tablebody1>北京东路668号B区901室</td>       ");
		out.print("			</tr>       ");
		out.print("			<tr>       ");
		out.print("				<td class=tablebody2 align='right'>邮编&nbsp:&nbsp</td>       ");
		out.print("				<td class=tablebody1>200001</td>       ");
		out.print("			</tr>       ");
		out.print("			<tr>       ");
		out.print("				<td class=tablebody2 align='right'>家庭电话&nbsp:&nbsp</td>       ");
		out.print("				<td class=tablebody1>61202663</td>       ");
		out.print("			</tr>       ");
		out.print("			<tr>       ");
		out.print("				<td class=tablebody2 align='right'>办公室电话&nbsp:&nbsp</td>       ");
		out.print("				<td class=tablebody1>61202663</td>       ");
		out.print("			</tr>       ");
		out.print("			<tr>       ");
		out.print("				<td class=tablebody2 align='right'>手机&nbsp:&nbsp</td>       ");
		out.print("				<td class=tablebody1>13211161676</td>       ");
		out.print("			</tr>       ");
		out.print("			<tr>       ");
		out.print("				<td class=tablebody2 align='right'>Email地址&nbsp:&nbsp</td>       ");
		out.print("				<td class=tablebody1>zhouyu@tarena.com.cn</td>       ");
		out.print("			</tr>       ");
		out.print("		</table>		       ");
		out.print("		       ");
		out.print("		<br>       ");
		out.print("		       ");
		out.print("		<table cellspacing='1' cellpadding='3' align='center' class='tableborder1'>       ");
		out.print("			<tr>       ");
		out.print("				<td valign='middle' align='center' height='25' background='images/bg2.gif' width='8%' colspan='2'>       ");
		out.print("					<font color='#ffffff' size='2pt'>       ");
		out.print("						<b>付款方式</b>       ");
		out.print("					</font>       ");
		out.print("				</td>       ");
		out.print("			</tr>       ");
		out.print("			<tr>       ");
		out.print("				<td class=tablebody2 align='center' width='40%'></td>       ");
		out.print("				<td class=tablebody1>       ");
		out.print("					<select name='邮局汇款'>       ");
		out.print("						<option value='0'>邮局汇款</option>       ");
		out.print("						<option value='1'>银行转帐</option>       ");
		out.print("						<option value='2'>货到付款</option>       ");
		out.print("					</select>       ");
		out.print("				</td>       ");
		out.print("			</tr>       ");
		out.print("		</table>       ");
		out.print("		       ");
		out.print("		<br>       ");
		out.print("		       ");
		out.print("		<table cellspacing='1' cellpadding='3' align='center' class='tableborder1'>       ");
		out.print("			<tr>       ");
		out.print("				<td valign='middle' align='center' height='25' background='images/bg2.gif' width='8%' colspan='5'>       ");
		out.print("					<font color='#ffffff' size='2pt'>       ");
		out.print("							<b>商品购物清单</b>       ");
		out.print("					</font>       ");
		out.print("					<input type='button' value='修改' onclick='javascript:window.location='../order/orderList';' >       ");
		out.print("				</td>       ");
		out.print("			</tr>       ");
		out.print("			<tr>       ");
		out.print("				<td class=tablebody2 align='center' width='3%'>1</td>       ");
		out.print("				<td class=tablebody1 width='52%'>精通Hibernate</td>       ");
		out.print("				<td class=tablebody2 width='15%'>价格&nbsp;:&nbsp;59.0</td>       ");
		out.print("				<td class=tablebody1 width='15%'>数量&nbsp;:&nbsp;1</td>       ");
		out.print("				<td class=tablebody2 width='15%'>小计&nbsp;:&nbsp;￥59</td>       ");
		out.print("			</tr>       ");
		out.print("			<tr>       ");
		out.print("				<td class=tablebody2 align='center' width='3%'>2</td>       ");
		out.print("				<td class=tablebody1 width='52%'>中文版</td>       ");
		out.print("				<td class=tablebody2 width='15%'>价格&nbsp;:&nbsp;39.0</td>       ");
		out.print("				<td class=tablebody1 width='15%'>数量&nbsp;:&nbsp;2</td>       ");
		out.print("				<td class=tablebody2 width='15%'>小计&nbsp;:&nbsp;￥78</td>       ");
		out.print("			</tr>       ");
		out.print("			<tr>       ");
		out.print("				<td class=tablebody1 align='center' colspan='4'></td>       ");
		out.print("				<td class=tablebody1>合计&nbsp:&nbsp<font color='red'>￥137</font></td>       ");
		out.print("			</tr>       ");
		out.print("		</table>       ");
		out.print("		       ");
		out.print("		<br>       ");
		out.print("		       ");
		out.print("		<table cellspacing='1' cellpadding='3' align='center' border='0' width='98%'>       ");
		out.print("			<tr>       ");
		out.print("				<td width='65%' align='center'>       ");
		out.print("					<b>请认真检查以上订单信息，确认无误后，点击&nbsp;→</b>       ");
		out.print("					<a href='../order/orderList'><img border='0' src='images/submit.gif'></a>       ");
		out.print("				</td>       ");
		out.print("			</tr>       ");
		out.print("		</table>       ");
		out.print("		       ");
		out.print("		<br>       ");
		out.print("		</form>       ");
		out.print("<!-- Body End -->       ");
		out.print("       ");
		out.print("<!-- Footer Start -->       ");
		out.print("		<table width='100%' border='0' cellspacing='0' cellpadding='0' align='center' height='28'>       ");
		out.print("			<tr>       ");
		out.print("				<td height='17' background='images/bot_bg.gif'>       ");
		out.print("				</td>       ");
		out.print("			</tr>       ");
		out.print("		</table>       ");
		out.print("		<table width='100%' border='0' cellspacing='0' cellpadding='0' align='center'>       ");
		out.print("			<tr>       ");
		out.print("				<td bgcolor='#f1f1f6' height='53' valign='center'>       ");
		out.print("					<p align='center'>       ");
		out.print("						Copyright &copy;2004 - 2005 <a href='http://www.tarena.com.cn'><b>Tarena</b><font color='red'>.com.cn</font></a>       ");
		out.print("					</p>       ");
		out.print("				</td>       ");
		out.print("			</tr>       ");
		out.print("		</table>       ");
		out.print("<!-- Footer End -->       ");
		out.print("       ");
		out.print("	</body>       ");
		out.print("</html>");
		out.close();		
		
		
	}


public void doPost(HttpServletRequest req, 
		HttpServletResponse resp) throws ServletException, IOException {


}


}
